### ISSUE TITLE
This model only works on concurrent speaker counting?

### ISSUE THREAD

**Issue by wachhu** [faroit/CountNet#12]
Hi Faroit, if I have a record of a conversation and they didn't talk at the same time, is it still working ？

**Comment by faroit** [comment]
hi @wachhu. the expected output of the scenario you mentioned would indeed be `1`. The use case you mentioned is a simpler one and is usually covered in tasks related to speaker-diarization, which was not the aim of this model. However, countnet can easily be retrained for this purpose if you are interested in it.
