### ISSUE TITLE
Is there any source code?

### ISSUE THREAD

**Issue by ahmadrv** [faroit/CountNet#14]
Hi there.
I found your work recently. I'm interested in source counting in speech and choose it for my bachelor project. I'm trying to improve it with better feature engineering with some new stuffs.

Until now i succeed to load CNN.h5 but it has many parameters that i couldn't train it well! Other attractive models like CRNN.h5, have problem in loading that i mention below:
`TypeError: ('Keyword argument not understood:', 'input_dtype')`

I would be grateful if you would let me to have source code for my work to improve CountNet.

Sincerely.

Email: [Ahmad Mahmoodian Darvishani](ahmadmahmoodiandarvishani@gmail.com)

**Comment by faroit** [comment]
Hi @ahmadrv. We can't provide the training code. I think that implementing the training is straightforward, if you have any questions, let me know here.

**Comment by ahmadrv** [comment]
> Hi @ahmadrv. So that we can't provide the training code. I think that implementing the training is straightforward, if you have any questions, let me know here. 

Thanks for reply.
