### ISSUE TITLE
couldn't load CRNN

### ISSUE THREAD

**Issue by ahmadrv** [faroit/CountNet#15]
Hi there,
when i run this:

> `python predict.py examples/5_speakers.wav --model CRNN`

returns:

> Traceback (most recent call last):
>   File "predict.py", line 69, in <module>
>     'exp': K.exp
>   File "/usr/local/lib/python3.7/dist-packages/keras/saving/save.py", line 202, in load_model
>     compile)
>   File "/usr/local/lib/python3.7/dist-packages/keras/saving/hdf5_format.py", line 181, in load_model_from_hdf5
>     custom_objects=custom_objects)
>   File "/usr/local/lib/python3.7/dist-packages/keras/saving/model_config.py", line 59, in model_from_config
>     return deserialize(config, custom_objects=custom_objects)
>   File "/usr/local/lib/python3.7/dist-packages/keras/layers/serialization.py", line 163, in deserialize
>     printable_module_name='layer')
>   File "/usr/local/lib/python3.7/dist-packages/keras/utils/generic_utils.py", line 672, in deserialize_keras_object
>     list(custom_objects.items())))
>   File "/usr/local/lib/python3.7/dist-packages/keras/engine/sequential.py", line 493, in from_config
>     custom_objects=custom_objects)
>   File "/usr/local/lib/python3.7/dist-packages/keras/layers/serialization.py", line 163, in deserialize
>     printable_module_name='layer')
>   File "/usr/local/lib/python3.7/dist-packages/keras/utils/generic_utils.py", line 675, in deserialize_keras_object
>     deserialized_obj = cls.from_config(cls_config)
>   File "/usr/local/lib/python3.7/dist-packages/keras/engine/base_layer.py", line 716, in from_config
>     return cls(**config)
>   File "/usr/local/lib/python3.7/dist-packages/keras/layers/convolutional.py", line 2859, in __init__
>     super(ZeroPadding2D, self).__init__(**kwargs)
>   File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/training/tracking/base.py", line 522, in _method_wrapper
>     result = method(self, *args, **kwargs)
>   File "/usr/local/lib/python3.7/dist-packages/keras/engine/base_layer.py", line 323, in __init__
>     generic_utils.validate_kwargs(kwargs, allowed_kwargs)
>   File "/usr/local/lib/python3.7/dist-packages/keras/utils/generic_utils.py", line 1134, in validate_kwargs
>     raise TypeError(error_message, kwarg)
> TypeError: ('Keyword argument not understood:', 'input_dtype')

Would you show me the problem?

**Comment by faroit** [comment]
how did you install the environment?

**Comment by ahmadrv** [comment]
> how did you install the environment?

`conda env create -f /CountNet/env.yml`

gives me:

    Solving environment: failed
    
    ResolvePackageNotFound: 
      - libcxx=10.0.0

additionally, running on Colab.

**Comment by ahmadrv** [comment]
> > how did you install the environment?
> 
> `conda env create -f /CountNet/env.yml`
> 
> gives me:
> 
> ```
> Solving environment: failed
> 
> ResolvePackageNotFound: 
>   - libcxx=10.0.0
> ```
> 
> additionally, running on Colab.


> how did you install the environment?

Thanks for the point.
I've loaded CRNN.h5 successfully.

**Comment by faroit** [comment]
okay great.
