### ISSUE TITLE
Is there any code about how to train the model?

### ISSUE THREAD

**Issue by aishoot** [faroit/CountNet#3]
Hello, 
     Thanks for your paper and code for speaker count estimation and it helps me a lot. Is there any code about how to train the model while there is only the code of prediction? Thanks!

**Comment by faroit** [comment]
Hi @pchao6, thanks for your interest in our research. For now we cannot share the code to train the network, but if you have some questions regarding the description in the paper, I am happy to answer them. Also, note that we provide the model in this project which you can also use to fine-tune or retrain the model.

**Comment by aishoot** [comment]
@faroit Thanks!
