### ISSUE TITLE
ImportError: nvcuda.dll

### ISSUE THREAD

**Issue by khrouatbi** [faroit/CountNet#5]
I'm getting the following error:

ImportError: Could not find 'nvcuda.dll'. TensorFlow requires that this DLL be installed in a directory that is named in your %PATH% environment variable. Typically it is installed in 'C:\Windows\System32'. If it is not present, ensure that you have a CUDA-capable GPU with the correct driver installed.

Any idea how to resolve this?
many thanks!

**Comment by faroit** [comment]
That looks like an error in your cuda installation. Maybe you can just try to run inference on CPU instead.
